name: gasfleet-client Check

on:
  pull_request:
    branches: [dev, pro]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);

  prettier:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run prettier:check

  build:
    runs-on: ubuntu-latest
    needs: install
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: k68zk0vr
      NEXT_PUBLIC_SANITY_DATASET: production
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build